title: This is a Joke Blog made for Learning Purposes Only (and not comedy.) (no sir.) (not at all.)
author: mgaren01
email: garen1989@gmail.com
description: > # this means to ignore newlines until "baseurl:"
The title says it all, dude.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
